services:
  api01:
    build: .
    environment:
      DATABASE_URL: "postgres://admin:123@db:5432/rinha?sslmode=disable"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "120MB"

  api02:
    build: .
    environment:
      DATABASE_URL: "postgres://admin:123@db:5432/rinha?sslmode=disable"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "120MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=200
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300MB"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
